### ISSUE TITLE
HW 25.02.19

### ISSUE THREAD

**Issue by evgrafoov** [ing-prog/webpy_2019_1_g1#2]
####Магический кот убрал этот код####

**Comment by vlasove** [comment]
Что выдаст твоя прога для случая A =0, B = 0, C = 1?

**Comment by vlasove** [comment]
Зачем тебе цикл while внутри функции def sol_nod (a, b)?

**Comment by evgrafoov** [comment]
1) Пофиксил. Теперь False
2) Проверка на 0 и выход из цикла

**Comment by evgrafoov** [comment]
Можно сделать бесконечный и выходить с помощью break

**Comment by vlasove** [comment]
Если хочешь except'ить ввод - то лучше каждый input запихивать в свой блок try/except .
Если я напишу A = 10 (valid) B = ÄSD (invalid) Прога попросит меня заново вводить и A и B.

**Comment by vlasove** [comment]
> Можно сделать бесконечный и выходить с помощью break

Там в принципе while ни к месту. Воспользуйся if

**Comment by vlasove** [comment]
Во второй задачe узнаю алгоритм Евклида - ее тестить не буду. Поправь только ввод с try\except и if вместо while в теле функции

**Comment by vlasove** [comment]
Первую задачу буду тестить, только чуть позже. Сделай плиз вывод следующим образом :
Если есть 2 корня  ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by evgrafoov** [comment]
Хорошо. Второе задание я сделал рекурсией.

**Comment by vlasove** [comment]
Да, я понял уже. К вечеру глаза замылись, но как я уже сказал - c ней все ок. Там зачет

**Comment by evgrafoov** [comment]
1 задание переделал вывод

**Comment by vlasove** [comment]
> 1 задание переделал вывод

1)Сними точность у флагов %0.2f оставь стандартную точность %f.
2) Прошло 3 теста всего. Думается мне, что символы + и -, которые ты добавляешь в print() лишние.

**Comment by evgrafoov** [comment]
1) Сделал
2) Сделать 2 переменные или выводить одну?

**Comment by vlasove** [comment]
> 1. Сделал
> 2. Сделать 2 переменные или выводить одну?

print ('+%f, -%f' %(x, x)) ---> print ('%f, %f' %(x, -x)) 

Уравнение с b= 0 остается квадратным, из этого следует количество корней, которое необходимо оставить

**Comment by evgrafoov** [comment]
Готово

**Comment by vlasove** [comment]
Красавчик. Зачет
