### ISSUE TITLE
Нерубащенко Максим, 25.02.19

### ISSUE THREAD

**Issue by ghost** [ing-prog/webpy_2019_1_g1#3]
1) https://github.com/jeWick/PythonCourses/blob/master/kvadr.py - Квадратное уравнение
2) https://github.com/jeWick/PythonCourses/blob/master/nod.py - НОД

**Comment by vlasove** [comment]
1)Для чего в коде (НОД) импортирована ось? (import os) Неиспользуемые пакеты нужно удалить.
2) Как будет вести прога, если подать ей на вход А=0, В = 1? Нод для такого случая = 1

**Comment by vlasove** [comment]
Квадратное уравнение --- рекомендую еще раз ознакомиться с условием задачи
https://github.com/ing-prog/webpy_2019_1_g1/blob/master/HW%2025.02/equation.py

Необходимо убрать условие на запрет ввода нулевых значений.
2) Для чего тебе опять здесь ось? Никакие здесь slope pause не используются.
3)  Сделай плиз вывод следующим образом (в задаче с уравнением) :
Если есть 2 корня ---- то выводится просто 2 числа через пробел или запятую (не важно)
Если корень 1 -- выводится только это число
Если корней нет -- пустая строка

**Comment by ghost** [comment]
в проге с квадратным ось используется, 2 паузы использую
остальное тогда переделаю, позже скину

**Comment by vlasove** [comment]
> в проге с квадратным ось используется, 2 паузы использую
> остальное тогда переделаю, позже скину

Для чего в задаче с нахождением корней паузы?

**Comment by ghost** [comment]
чтобы когда программа выведет корни, вы смогли проверить, иначе программа вылетает, и консоль закрывается)

**Comment by vlasove** [comment]
> чтобы когда программа выведет корни, вы смогли проверить, иначе программа вылетает, и консоль закрывается)

Я проверяю только сруктуру твоего кода и его читаемость, затем кидаю твое решение в свой скрипт, который тестит твою прогу. Ей не нужны паузы, чтобы сказать, ок решение или не ок

**Comment by ghost** [comment]
Ну я не знал, мне то они нужны, чтобы проверить рез-ты, я и оставил
Хорошо, исправлю

**Comment by ghost** [comment]
Пофиксил баги прог

**Comment by vlasove** [comment]
Красавчик! Зачет за дз
