### ISSUE TITLE
Белоглазов Даниил

### ISSUE THREAD

**Issue by Beloglaz0v** [ing-prog/webpy_2019_1_g1#6]
https://github.com/K0ur/techopark/tree/master/week1

**Comment by vlasove** [comment]
Уравнение падает на вводе 0 1 0

**Comment by Beloglaz0v** [comment]
исправил

**Comment by Beloglaz0v** [comment]
а с нодом всё нормально?

**Comment by vlasove** [comment]
Ок, успел исправить. Зачет
